
CREATE TABLE IF NOT EXISTS pages (
    id SERIAL,
    title TEXT,
    description TEXT,
    keywords TEXT,
    tags TEXT,
    parent_id BIGINT NOT NULL default 0,
    sort_order INT NOT NULL default 0,
    content MEDIUMTEXT,
    styles MEDIUMTEXT,
    scripts MEDIUMTEXT,
    template BIGINT,
    developer_lock BOOL NOT NULL DEFAULT 0,
    admin_lock BOOL NOT NULL DEFAULT 0,
    live BOOL NOT NULL DEFAULT 0,
    live_from DATETIME,
    live_until DATETIME,
    redirect TEXT,
    modification_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    creation_date TIMESTAMP NOT NULL,
    PRIMARY KEY (id),
    KEY title (title(255)),
    KEY tags (tags(255)),
    KEY live (live),
    KEY live_from (live_from),
    KEY live_until (live_until),
    KEY template (template),
    KEY parent_ (parent_id),
    KEY sort_order (sort_order)
) ENGINE=MyISAM CHARSET=utf8;